source 'http://rubygems.org'

gem "json"
gem "sinatra"
gem "rack"
gem "rack-cors"
# gem "sinatra-cross_origin"
gem "twitter"
# gem "tweetstream"
gem "omniauth"
gem "omniauth-twitter"
# gem "foreman"
# gem "unicorn"
# gem "rerun"
gem "pry"
